### PR TITLE
Cleanup/refactor template content model impl

### PR DESCRIPTION
**Pull request by josecarlosgt**
Code organization in this class included:

- Ordering methods and properties by visibility
- Removing unused methods, imports, and invalid comments
- Adding blank lines to enhance code readability
- Most protected methods were converted to private

### CODE REVIEW

**Comment by josecarlosgt** [comment]
Several issues mentioned in #4 and [DantaFramework/AEM#8](https://github.com/DantaFramework/AEM/issues/8) are still needed to be addressed before completing this task. Pending issues are:

- Review whether synchronized methods and volatile fields are necessary
- Move duplicated code with AEM implementation to Core project

**Review by jbarrera-xumak — COMMENTED** [review]
+1

**Comment by jbarrera-xumak** [comment]
The synchronized methods are necessary for the execution of context processors in parallel stream to work well.

And for volatile fields, what do you think @joransky-xk  and @neozilon?

**Comment by josecarlosgt** [comment]
Common functionality with AEM has been moved to Core in [PR #22](https://github.com/DantaFramework/Core/pull/22) . Essentially, only code related to the request and response properties remain in this class.

**Comment by josecarlosgt** [comment]
Tested many times by deleting and installing the bundles. Further testing is recommended as this PR involves significant changes to the template content model implementation.

**Comment by josecarlosgt** [comment]
As requested by @jbarrera-xumak , commits on this PR were re-based to master. This is, commits on this PR were moved ahead of the commits currently on master. Please note that Core needs to be updated for this PR to deploy successfully.

**Review by jbarrera-xumak — APPROVED** [review]
+1

**Pull request merged**
