### PR TITLE
Feature/statistics cp

### PR DESCRIPTION
**Pull request by josecarlosgt**
This servlet displays the CPs executed for a given resource. At the moment, it only works for component resources (not pages). For example,

- http://localhost:8080/cms/render/default/en/sites/newDanta/home/content-section-home/title.contentmodel.statistics.do

Allowing page resources would require a different CP and a different servlet since page resoruces are managed in a different way by JahiaDF.

### CODE REVIEW

**Comment by josecarlosgt** [comment]
TODO: Needs to specify this CP should validate the clientAccessible property.

**Comment by neozilon** [comment]
should we wait to do the validation before approving the PR ? or will you open another one ?

**Comment by josecarlosgt** [comment]
I've talked with @jbarrera-xumak and the validation is not necessary. However, I will add the functionality to resolve statistics for page resources as well on the same servlet. I will add this functionality on this PR.

**Comment by neozilon** [comment]
ok, let me know when it is done so we can merge it

**Comment by josecarlosgt** [comment]
Done. Serlvet now handles page resources as well. Example:

http://localhost:8080/cms/render/default/en/sites/newDanta/home.contentmodel.statistics.do

**Review by neozilon — APPROVED** [review]
+1

**Pull request merged**
